---
- name: Download and install latest packages locally
  hosts: localhost
  connection: local
  gather_facts: false          # <- prevents the setup task (the source of the error)
  become: false                # <- no global sudo; we add it per task

  vars:
    package_list_path: /full/path/to/packages.txt   # <-- set absolute path
    download_dir: /var/tmp/rpm_downloads
    download_dependencies: true

    package_list: >-
      {{
        lookup('file', package_list_path)
        .splitlines()
        | map('trim')
        | reject('match','^#')
        | reject('equalto','')
        | list
      }}

  tasks:
    - name: Ensure dnf download plugin is installed
      become: yes
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Create directory for downloads
      become: yes
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        mode: "0755"

    - name: Download the latest RPMs for listed packages
      ansible.builtin.command: >
        dnf download
        {{ '--resolve' if download_dependencies else '' }}
        --downloaddir={{ download_dir }}
        {{ item }}
      args:
        warn: false
      loop: "{{ package_list }}"
      changed_when: true

    - name: Install/Update to latest versions
      become: yes
      ansible.builtin.dnf:
        name: "{{ package_list }}"
        state: latest
